### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [ealhajsalem/pwp-capstones#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations) 
* _Comment(s):_ Code can be run fully without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 3 (Meets Expectations) 
* _Comment(s):_ Code produces between most of functions and classes, but seems to be missing some methods for the _TomeRater_ class.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds Expectations) 
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes.

### Criteria 4: Uses Python Language Features
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Python language features are usually used, but there are 1-3 cases of a coded construction could have been accomplished by a Python builtin. For example, in the _Book_ class's [get_average_rating()](https://github.com/ealhajsalem/pwp-capstones/blob/master/for_code_academy/TomeRater.py#L95-L100) method, you could use the builtin `sum()` function to get `average_book_rating_total` (instead of calculating it using the loop): 
```
average_book_rating_total = sum(self.ratings)
```
 
### Overall Score: 14/16
Well done on this project! You definitely have a good sense of how to organize and structure your code. And great idea to [test your code](https://github.com/ealhajsalem/pwp-capstones/blob/master/for_code_academy/TomeRater.py#L211-L261) as you write it!

One thing you could look out for are ways to simplify your code, such as by utilizing built-in functions. You could also try avoiding creating extra redundant instance attributes. For example, this:
https://github.com/ealhajsalem/pwp-capstones/blob/378a3c1ad56f861d849daa2d93edff7b319e1944/for_code_academy/TomeRater.py#L23-L24
could be simplified to:
```python
self.email = address
```

And as a further challenge, try implementing all the remaining methods in your _TomeRater_ class. Have fun! :)

**Comment by ealhajsalem** [comment]
Thanks for the comments , i hope i will enhance in future .. regarding the missing method is because i got busy at work and couldn't finish at the time.

Regards
Emad
